package com.raythinks.poesia.ui.model

/**
 * Created by 赵海 on 2017/10/9.
 */

data class AuthorPoesiaModel(var sumCount: Int = 0,
                             var sumPage: Int = 0,
                             var currentPage: Int = 0,
                             var tb_author: AuthorsItem? = null,
                             var tb_gushiwens: ArrayList<GushiwensItem>? = null) {

    /**
     * sumCount : 628
     * sumPage : 63
     * currentPage : 1
     * tb_author : {"id":217,"nameStr":"辛弃疾","cont":"　　辛弃疾（1140－1207），南宋词人。原字坦夫，改字幼安，别号稼轩，汉族，历城（今山东济南）人。出生时，中原已为金兵所占。21岁参加抗金义军，不久归南宋。历任湖北、江西、湖南、福建、浙东安抚使等职。一生力主抗金。曾上《美芹十论》与《九议》，条陈战守之策。其词抒写力图恢复国家统一的爱国热情，倾诉壮志难酬的悲愤，对当时执政者的屈辱求和颇多谴责；也有不少吟咏祖国河山的作品。题材广阔又善化用前人典故入词，风格沉雄豪迈又不乏细腻柔媚之处。由于辛弃疾的抗金主张与当政的主和派政见不合，后被弹劾落职，退隐江西带湖。","chaodai":"宋代","pic":"xinqiji","likes":2036,"ipStr":"user:147298","creTime":"/Date(-62135596800000)/"}
     * tb_gushiwens : [{"id":57601,"nameStr":"青玉案·元夕","author":"辛弃疾","chaodai":"宋代","cont":"东风夜放花千树。更吹落、星如雨。宝马雕车香满路。凤箫声动，玉壶光转，一夜鱼龙舞。 <br></br>蛾儿雪柳黄金缕。笑语盈盈暗香去。众里寻他千百度。蓦然回首，那人却在，灯火阑珊处。 ","axing":1664,"bxing":503,"cxing":570,"dxing":991,"exing":10319,"type":null,"tag":"宋词三百首|婉约|元宵节|写人","langsongAuthor":"蒋伟伟","langsongAuthorPY":"jiangweiwei","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"徐中玉 金启华 ．中国古代文学作品选（二） ．上海 ：华东师范大学出版社 ，1999 ：144-146 ．& 陆林编注 ．宋词 ．北京 ：北京师范大学出版社 ，1992 ：204-205 ．& 蘅塘退士 等 ．唐诗三百首·宋词三百首·元曲三百首 ．北京 ：华文出版社 ，2009 ：287 ．","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true},{"id":57913,"nameStr":"破阵子·为陈同甫赋壮词以寄之","author":"辛弃疾","chaodai":"宋代","cont":"醉里挑灯看剑，梦回吹角连营。八百里分麾下炙，五十弦翻塞外声。沙场秋点兵。<br></br>马作的卢飞快，弓如霹雳弦惊。了却君王天下事，赢得生前身后名。可怜白发生！ ","axing":1706,"bxing":563,"cxing":679,"dxing":1051,"exing":9638,"type":null,"tag":"宋词三百首|初中古诗|豪放|记梦|战争|抒情|壮志难酬","langsongAuthor":"易叶声","langsongAuthorPY":"yiyesheng","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"王烈夫．宋代诗词名作注解析译．武汉：武汉大学出版社，1994年7月版：第201-202页&陆林编注．宋词．北京：北京师范大学出版社，1992年11月版：第198-199页&杨忠译注．辛弃疾词选译．成都：巴蜀书社，1991年10月版：第166-168页&李静 等．唐诗宋词鉴赏大全集．北京：华文出版社，2009年11月版：第356-357页","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true},{"id":57678,"nameStr":"西江月·夜行黄沙道中","author":"辛弃疾","chaodai":"宋代","cont":"明月别枝惊鹊，清风半夜鸣蝉。稻花香里说丰年，听取蛙声一片。 <br></br>七八个星天外，两三点雨山前。旧时茅店社林边，路转溪桥忽见。(溪桥 一作：溪头) ","axing":2161,"bxing":664,"cxing":750,"dxing":1157,"exing":8822,"type":null,"tag":"宋词三百首|小学古诗|初中古诗|婉约|豪放|夏天|农村|","langsongAuthor":"蒋伟伟","langsongAuthorPY":"jiangweiwei","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"程帆．唐诗宋词鉴赏辞典：湖南教育出版社，2010：578-579","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true},{"id":57611,"nameStr":"清平乐·村居","author":"辛弃疾","chaodai":"宋代","cont":"
     *
     *茅檐低小，溪上青青草。<br></br>醉里吴音相媚好，白发谁家翁媪？<br></br>大儿锄豆溪东，中儿正织鸡笼。<br></br>最喜小儿亡赖，溪头卧剥莲蓬。(亡 通：无)<\/p>","axing":1749,"bxing":501,"cxing":607,"dxing":790,"exing":6139,"type":null,"tag":"宋词三百首|小学古诗|初中古诗|向往|乡村|生活","langsongAuthor":"蒋伟伟","langsongAuthorPY":"jiangweiwei","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"徐中玉 金启华．中国古代文学作品选（二）．上海：华东师范大学出版社，1999：146-147&杨忠译注．辛弃疾词选译．成都：巴蜀书社，1991：144-145&蘅塘退士 等．唐诗三百首·宋词三百首·元曲三百首．北京：华文出版社，2009：281","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true},{"id":58029,"nameStr":"南乡子·登京口北固亭有怀","author":"辛弃疾","chaodai":"宋代","cont":"何处望神州？满眼风光北固楼。千古兴亡多少事？悠悠。不尽长江滚滚流。<br></br>年少万兜鍪，坐断东南战未休。天下英雄谁敌手？曹刘。生子当如孙仲谋。 ","axing":797,"bxing":264,"cxing":355,"dxing":557,"exing":4723,"type":null,"tag":"宋词三百首|初中古诗|豪放|咏史怀古|爱国|典故|讽刺","langsongAuthor":"","langsongAuthorPY":"","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"陆林编注 ．宋词 ．北京 ：北京师范大学出版社 ，1992 ：211-212 ．& 李静 等 ．唐诗宋词鉴赏大全集 ．北京 ：华文出版社 ，2009 ：357 ．& 蘅塘退士 等 ．唐诗三百首·宋词三百首·元曲三百首 ．北京 ：华文出版社 ，2009 ：279 ．","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true},{"id":57989,"nameStr":"永遇乐·京口北固亭怀古","author":"辛弃疾","chaodai":"宋代","cont":"千古江山，英雄无觅，孙仲谋处。舞榭歌台，风流总被雨打风吹去。斜阳草树，寻常巷陌，人道寄奴曾住。想当年，金戈铁马，气吞万里如虎。<br></br>元嘉草草，封狼居胥，赢得仓皇北顾。四十三年，望中犹记，烽火扬州路。可堪回首，佛狸祠下，一片神鸦社鼓。凭谁问，廉颇老矣，尚能饭否？ ","axing":766,"bxing":261,"cxing":301,"dxing":551,"exing":4605,"type":null,"tag":"宋词三百首|豪放|咏史怀古|爱国|讽刺|慨叹","langsongAuthor":"","langsongAuthorPY":"","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"历鹗（词整理）、赵彦（赏析整理） ．辛弃疾词赏析全集 ：接力出版社 ，2008年 ：201-204 ．","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true},{"id":57795,"nameStr":"丑奴儿·书博山道中壁","author":"辛弃疾","chaodai":"宋代","cont":"少年不识愁滋味，爱上层楼。爱上层楼。为赋新词强说愁。 <br></br>而今识尽愁滋味，欲说还休。欲说还休。却道天凉好个秋。 ","axing":426,"bxing":154,"cxing":195,"dxing":326,"exing":3347,"type":null,"tag":"宋词三百首|宋词精选|婉约|写人|少年|抒怀|愁苦","langsongAuthor":"","langsongAuthorPY":"","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"李静 等．唐诗宋词鉴赏大全集．北京：华文出版社，2009：356&陆林编注．宋词．北京：北京师范大学出版社，1992：207-208","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true},{"id":57580,"nameStr":"菩萨蛮·书江西造口壁","author":"辛弃疾","chaodai":"宋代","cont":"郁孤台下清江水，中间多少行人泪。西北望长安，可怜无数山。<br></br>青山遮不住，毕竟东流去。江晚正愁余，山深闻鹧鸪。 (愁余 一作：愁予) ","axing":739,"bxing":251,"cxing":309,"dxing":407,"exing":2946,"type":null,"tag":"宋词三百首|豪放|山水|抒怀|爱国","langsongAuthor":"","langsongAuthorPY":"","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"陆林编注．宋词．北京：北京师范大学出版社，1992年11月版：第203页&李静 等．唐诗宋词鉴赏大全集．北京：华文出版社，2009年11月版：第362页&蘅塘退士 等．唐诗三百首·宋词三百首·元曲三百首．北京：华文出版社，2009年11月版：第278页","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true},{"id":57521,"nameStr":"水龙吟·登建康赏心亭","author":"辛弃疾","chaodai":"宋代","cont":"
     *
     *楚天千里清秋，水随天去秋无际。遥岑远目，献愁供恨，玉簪螺髻。落日楼头，断鸿声里，江南游子。把吴钩看了，栏杆拍遍，无人会，登临意。(栏杆 一作：阑干)<br></br>休说鲈鱼堪脍，尽西风，季鹰归未？求田问舍，怕应羞见，刘郎才气。可惜流年，忧愁风雨，树犹如此！倩何人唤取，红巾翠袖，揾英雄泪！<\/p>","axing":287,"bxing":113,"cxing":124,"dxing":254,"exing":1640,"type":null,"tag":"宋词精选|高中古诗|豪放|写景|爱国|壮志","langsongAuthor":"","langsongAuthorPY":"","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"朱德才 ．《辛弃疾词选》 ：人民文学出版社1988年版 ，1998 ．& 历鹗（词整理）、赵彦（赏析整理） ．辛弃疾词赏析全集 ：接力出版社 ，2008年 ：13-15 ．","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true},{"id":57567,"nameStr":"鹧鸪天·送人","author":"辛弃疾","chaodai":"宋代","cont":"唱彻《阳关》泪未干，功名馀事且加餐。浮天水送无穷树，带雨云埋一半山。<br></br>今古恨，几千般，只应离合是悲欢？江头未是风波恶，别有人间行路难！ ","axing":174,"bxing":59,"cxing":64,"dxing":124,"exing":822,"type":null,"tag":"宋词精选|送别|感伤","langsongAuthor":"","langsongAuthorPY":"","yizhu":"9933003333ff","yizhuAuthor":"佚名","yizhuCankao":"周汝昌．《唐宋词鉴赏辞典》（南宋·辽·金卷）．上海：上海辞书出版社，1988年版：1496-1499","yizhuYuanchuang":false,"yizhuIspass":true,"shangIspass":true}]
     */


}
